# SYSTEM SETTINGS
VERSION = 5.0
FPS = 100

# DIR SETTINGS
SPRITES_DIR = 'sprites'
SYSTEM_DIR = 'system'
MUSIC_DIR = 'music'
UI_DIR = 'ui'

# WINDOW SETTINGS
WIDTH, HEIGHT = 1400, 800
WINDOW_TITLE = f"TaxiHell – Yandex LMS (v{VERSION})"
ICON = "icon.jpg"

# DATABASE SETTINGS
DATABASE_NAME = "saving.txt"